[Rainmeter]
Update=1000
AccurateText=1

[Metadata]
Name=Battery Warning
Author=cobalt-core
Information=Gives a warning when battery percent goes below X (user-input value) & warns you when battery percent is at 100 to unplug! :: Move the cursor to the 'charge?'/'switch to battery' to hide the warning. 
License=Creative Commons BY-NC-SA 3.0
Version=1.0.0

[Variables]
@Include=#@#one.inc

[styleTitle]
StringAlign=Left
StringCase=Upper
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,50
FontColor=#PALETTE4#
FontFace=#FACE1#
FontSize=10
AntiAlias=1
ClipString=1

[styleText]
StringAlign=Left
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,20
FontColor=#PALETTE4#
FontFace=#FACE1#
FontSize=6
AntiAlias=1
ClipString=1

[TitleBar]
Meter=Shape
Shape=Rectangle 1,1,200,30 | Fill Color #PALETTE1#,252 
Hidden=1
Group=A

[Fill]
Meter=Shape
Shape=Rectangle 1,1,200,79 | Fill Color #PALETTE2#,200
Hidden=1
Group=A

[Outline]
Meter=Shape
Shape=Rectangle 1,1,200,79 | Fill Color 0,0,0,0 | Stroke Width 4 | Stroke Color #PALETTE3#
Hidden=1
Group=A

[meterTitle]
Meter=String
MeterStyle=styleTitle
X=10
Y=12
W=400
H=18
FontSize=7
Text=  X _
Hidden=1
Group=A

;-------------------------------------------------------------
;change 20 to any other value (value must be above 20)
;in battery level : (20)
;-------------------------------------------------------------

[meterLine]
Meter=String
MeterStyle=styleText
X=10
Y=40
W=225
H=175
FontColor=#PALETTE4#
FontSize=6
Text=battery level low
Hidden=1
Group=A

[meterLine2]
Meter=String
MeterStyle=styleText
X=10
Y=56
W=225
H=175
FontColor=#PALETTE7#
FontSize=8
Text=charge?
Group=A
Hidden=1
MouseOverAction=!HideMeterGroup A

;-------------------------------------------------------------
;change 20 to any other value (value must be above 20)
;in battery level = (20)
;-------------------------------------------------------------

[BatteryLevel]
Measure=Plugin
Plugin=PowerPlugin
PowerState=Percent
IfCondition=(BatteryLevel = 20)
IfTrueAction=[!ShowMeterGroup A]

;-------------------------------------------------------------
;OVERCHARGING WARNING
;-------------------------------------------------------------

[TitleBar2]
Meter=Shape
Shape=Rectangle 1,1,200,30 | Fill Color #PALETTE1#,252 
Hidden=1
Group=B

[Fill2]
Meter=Shape
Shape=Rectangle 1,1,200,79 | Fill Color #PALETTE2#,200
Hidden=1
Group=B

[Outline2]
Meter=Shape
Shape=Rectangle 1,1,200,79 | Fill Color 0,0,0,0 | Stroke Width 4 | Stroke Color #PALETTE3#
Hidden=1
Group=B

[meterTitle1]
Meter=String
MeterStyle=styleTitle
X=10
Y=12
W=400
H=18
FontSize=7
Text=  X _
Hidden=1
Group=B

[meterLine1]
Meter=String
MeterStyle=styleText
X=10
Y=40
W=225
H=175
FontColor=#PALETTE4#
FontSize=6
Text=battery level high
Hidden=1
Group=B
MouseOverAction=!HideMeterGroup B

[meterLine21]
Meter=String
MeterStyle=styleText
X=10
Y=56
W=225
H=175
FontColor=#PALETTE7#
FontSize=8
Text=plug off from charge?
Group=B
Hidden=1
MouseOverAction=!HideMeterGroup B

[BatteryLevel1]
Measure=Plugin
Plugin=PowerPlugin
PowerState=Percent
IfCondition=(BatteryLevel = 100)
IfTrueAction=[!ShowMeterGroup B]
